### ISSUE TITLE
Make Call To Function On Next Button Click

### ISSUE THREAD

**Issue by SushantVarshney** [DaveWM/ngWizard#11]
I want to call a function in Wizard Controller on Next Button Click like we do on Submit Button in this wizard.

**Comment by DaveWM** [comment]
You can do this by adding a `$scope.$watch` for the number you have bound to the wizard `current-step-number`. If you only want the function to be called when the user goes to the next step, check that the new step number is the old step number + 1

**Comment by SushantVarshney** [comment]
Can u make a dummy for the same thing you want to say.I am not getting how to do it????

**Comment by DaveWM** [comment]
See [this plunk](https://plnkr.co/edit/vByiYiaLRcFXfs2JjiK2?p=preview), I've added some code on line 3 of `app.js`
