### ISSUE TITLE
How to turn off tooltips?

### ISSUE THREAD

**Issue by stevehealy** [DaveWM/ngWizard#14]
Is there a way to stop "Step 1", "Step 2", etc, appearing as a tooltip when the user hovers over each wizard step section? I tried to remove all of the 720kb.tooltips code but it still appears. Thanks.

![image](https://cloud.githubusercontent.com/assets/6011483/21688353/77ad586c-d364-11e6-91ce-a2b2420bc6f0.png)

**Comment by DaveWM** [comment]
@stevehealy It's caused by the `title` attribute on the `wizard-step` element, which collides with the HTML [title attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title). Just use `data-title` instead to avoid the tooltip.

**Comment by stevehealy** [comment]
Perfect, thanks.
