### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by MadEddieFFS** [DaveWM/ngWizard#16]
I need to not allow navigation from a step unless users have checked a specific checkbox. How can i interact with the form which is created for each step so that I can intercept and control the validation?

**Comment by DaveWM** [comment]
ngWizard uses the standard angular form validation, so the advice given [here](http://stackoverflow.com/questions/28053426/checkbox-unchecked-to-make-form-invalid) should work. Basically, just add the `ng-model` directive and the `required` attribute to the checkbox. I've made a plunk [here](https://plnkr.co/edit/kCPImNosmmSWQ3AOYAYA?p=preview).

**Comment by MadEddieFFS** [comment]
Thanks for the detailed response Dave - I have forked your plunk [here](https://plnkr.co/edit/4nyBDKyZLI5ku7Z4WFI0?p=preview) as it now represents my issue accurately. The problem being - you are able to continue to the next step even though the form is not complete - Although I beleive the issue to be with Angular validation rather than your wizard.

Sorry - figured it out :) [solution](https://plnkr.co/edit/4nyBDKyZLI5ku7Z4WFI0?p=preview)

**Comment by DaveWM** [comment]
@MadEddieFFS Yeah, that is to do with angular's validation rather than the wizard, glad you got it sorted out :)
