### ISSUE TITLE
Failed to load template: template/tooltip/tooltip-popup.html 

### ISSUE THREAD

**Issue by shrutiaggarwal3012** [DaveWM/ngWizard#4]
I got this error " Failed to load template: template/tooltip/tooltip-popup.html " when i tried to use ngWizard. Any clue why this happen?

**Comment by DaveWM** [comment]
@shrutiaggarwal3012 how are you importing UI bootstrap? If you're using a script tag, are you loading the `ui-bootstrap-tpls-x.x.x` file? If you're using the `ui-bootstrap-x.x.x` (without -tpls-) file you'll get this error. See [here](https://github.com/angular-ui/bootstrap/wiki/FAQ#im-using-modal-service-but-it-cant-find-its-templates)

**Comment by DaveWM** [comment]
also, see #5, which should make installing ngWizard a bit easier when it's done

**Comment by DaveWM** [comment]
If you reinstall ngWizard it should now work, even without ui bootstrap
