### ISSUE TITLE
Error: [$parse:syntax] Syntax Error: Token '1' is an unexpected token at column 6 of the expression [step 1] starting at [1].

### ISSUE THREAD

**Issue by amenzoweb** [DaveWM/ngWizard#8]
Hello, firstly thank you for this nice one directive , im trying to use your nice directive : but i still get error for each step i have in my wizard : 
- Im using : Angular 1.4.8
- all needed module and directive injected
- it still works except the round icon steps not shown but next and pervious buttons are shown and works fine. 

Error: [$parse:syntax] Syntax Error: Token '1' is an unexpected token at column 6 of the expression [step 1] starting at [1].

```
<i class="fa ng-scope" ng-class="{'fa-circle-o disabled': getStepState(step) == stepStatesEnum.disabled, 'fa-circle': getStepState(step) == stepStatesEnum.complete, 'fa-circle-o': getStepState(step) == stepStatesEnum.ready, selected: getCurrentStep() == step}" ng-click="goToStepByReference(step)">
```

i have 3 steps like in your demo : and i have 3 errors in console. im not very good in angularjs could you help me to fix that please?

Thank you so much

**Comment by DaveWM** [comment]
Hi @amenzoweb, I can't seem to reproduce this issue, are you able to create a plunk/codepen which reproduces this error?

**Comment by DaveWM** [comment]
@amenzoweb Actually, think I've found the error. On the `wizard` element, do you have an attribute like `current-step-number="step 1"`? If you do, change it to `current-step-number="some_controller_variable"`, or remove the attribute entirely if you don't need the current step number on your controller's scope.
