### ISSUE TITLE
Not Able to use ngWizard on modal with ng-view

### ISSUE THREAD

**Issue by SushantVarshney** [DaveWM/ngWizard#9]
I want to make a wizard form which will get open on a Modal and the angular-routing is used.When I click on Next button of wizard form it get's redirect to the .otherwise url in my routing..
Please suggest.......

**Comment by DaveWM** [comment]
@SushantVarshney I think this was caused by the `href` attrs on the previous and next buttons. I've removed them, can you upgrade to version 1.0.1 and try again please?

**Comment by SushantVarshney** [comment]
Thnkxx ...it's working now  and I m closing the same.
